{
 "title": "Cloud MLOps Platform Dashboard",
 "tags": [
  "mlops",
  "production",
  "fastapi"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "MLOps Platform KPI Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Prediction Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(prediction_requests_total)", "legendFormat": "Total Predictions" }
   ]
  },
  {
   "title": "Current Max Drift Score (PSI)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(drift_score)", "legendFormat": "Max PSI Drift Score" }
   ]
  },
  {
   "title": "Total Drift Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(drift_alerts_total)", "legendFormat": "Drift Alerts" }
   ]
  },
  {
   "title": "Completed Training Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(training_jobs_total)", "legendFormat": "Training Jobs" }
   ]
  },
  {
   "title": "Real-Time Prediction Observability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Prediction Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(prediction_requests_total[1m])",
     "legendFormat": "{{model_name}} ({{status}})"
    }
   ]
  },
  {
   "title": "Inference Latency Average (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prediction_latency_seconds_sum[1m]) / rate(prediction_latency_seconds_count[1m])",
     "legendFormat": "{{model_name}} Avg Latency"
    }
   ]
  }
 ]
}