apiVersion: v1
kind: Service
metadata:
  name: mlops-backend-service
  labels:
    app: mlops-backend
spec:
  type: ClusterIP
  selector:
    app: mlops-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
